// react-app/src/views/Home.tsx
import * as React from 'react';

interface Props {
    framework: String;
};

interface State {
  welcomeMessage: String;
};

export default class Home extends React.Component<Props, State> {
  state: State = {
    welcomeMessage: 'Hello from '
  };

  render () {
    return (
      <div>
          <span>{this.state.welcomeMessage}</span>
          <span>{this.props.framework}</span>
      </div>
    );
  }
}

// vue-app/src/views/Home.vue
<template>
  <div>
    <span>{{welcomeMessage}}</span>
    <span>{{framework}}</span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface State {
  welcomeMessage: string;
}

export default defineComponent({
  name: "Home",
  
  props: {
    framework: String,
  },

  data: (): State => {
    return {
      welcomeMessage: 'Hello from ',
    }
  }
  
});
</script>
