// react-app/src/views/Props.tsx
import * as React from 'react';
import Highlight from 'react-highlight'


interface Props {};
interface State {};

export default class PropsExample extends React.Component<Props, State> {
 
  render () {
    return (
        <div>
            <h1>Component data, methods and properties</h1>

            <p>
                React Components are special objects that could have properties and methods.
                We can treat them as a ES6 classes. They receives external properties that are often 
                called as "props". That are something similar to the attributes of HTML elements
                that can be used to customize the component.
            </p>

            <h2>Component internal data</h2>

            

            <p>
                Each component could have its "state"
                that allows them to keep something in memory. To do that we must define
                the "state" property in the constructor. Because we are extending the
                React.Component class we have to keep in mind that the constructor 
                receives the "props" argument and the super() method must be called with 
                that argument. Using JSX syntax we can access to out state variables using 
                <code>this.state.welcomeMessage</code> reference that is placed within 
                <code>{ "{ }" }</code> braces. That inform the renderer method to place 
                there a value of that variable.
            </p>

            <Highlight className="javascript">
                {`export default ExampleProps extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            welcomeMessage: 'React property!',
        }
    }
    render() {
        return <h1>Hello from {this.state.welcomeMessage}</h1>
    }
}`}
            </Highlight>

            <h2>Passing properties</h2>

            <p>
                This time I should explaining with passing a external properties to the component
                but to keep it organized like it is presented in other frameworks I had to start 
                from the "state" property. But let's go to "props"! Props as it was mentioned 
                at the beginning are the external properties that we can pass to the component.
                By default they are accessible within the component using the "this.props" reference.
                But if we create a constructor method we have to remember to call the super() method
                with the "props" argument to not lose the reference to the "props" object. What is more
                the basic React component could be a simple function that receives the "props" as the argument
                and return the JSX code. That kind of component is called a "function component".
            </p>

            <Highlight className="javascript">
                {`function FunctionComponent(props) {
    return <h1>Hello from {props.framework}</h1>;
}`}
            </Highlight>

            <p>
                This time we are not defining the "props" that we are going to receive.
                We can add some props to the render method but we have to be aware 
                that it must be provided during the component creation.
            </p>

            <Highlight className="javascript">
                {`export default ExampleProps extends React.Component {
    render() {
        return <h1>Hello from {this.props.welcomeMessage}</h1>
    }
}`}
            </Highlight>

            <Highlight className="javascript">
                {`element = <ExampleProps welcomeMessage="React child component" />
`}
            </Highlight>

            <p>
                Wen we call ReactDOM.render() method the <code>ExampleProps</code> component
                is going to be rendered with the <code>welcomeMessage</code> property received
                from parent element. So it will render the header with text: "Hello from React child component".
            </p>

            <h3>Passing Variables</h3>

            <p>
                Using the same approach we can pass variables to the JSX template we can pass it to the 
                child component. In this case we are going to pass the variable <code>{ "framework" }</code>
                to the child ExampleProps component. It is very simple and easy to understand because 
                it is based on plain JavaScript and JSX methodology. Knowning that simple relation we are
                able to provide variables to our components.
            </p>

            <Highlight className="javascript">
                {`export default PropsParent extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            framework: 'React',
        }
    }
    render() {
        return <ExampleProps welcomeMessage={this.state.framework} />
    }
}`}
            </Highlight>

            <h2>Emitting Events</h2>

            <p>
                In the previous section we have seen how to pass properties to the component.
                But sometimes we need to emit events to the parent component. In React that
                could be more complex but I will try to explain it as simple as possible.
            </p>

            <p>
                From the beginning we have to create a method inside SingleEmit component that 
                will be called when the button is clicked. To intercept the onClick event we 
                are going to use the "onClick" attribute on the button tag. Now because 
                we want to use methods inside a class we have to use <code>{ "{ }" }</code>
                braces to inform render method that we are going to use a JavaScript there.
            </p>

            <p>
                We are going to create a arrow function that will invoke the <code>increaseNumber()</code>
                method whenever the button is clicked. That method will increase the state of the 
                <code>currentValue</code> property of the SingleEmit component. Then we are going to 
                emit the event to the parent. To do that we are going to use the "this.props" reference
                and then the <code>increasedEvent</code> property will be the name of the event that
                we are going to emit. Because we want to pass the current value of that coutner to the
                parent we provide the reference to the <code>currentValue</code> property as the function argument.
            </p>

            <Highlight className="javascript">
                {`export default SingleEmit extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            currentValue: 0,
        }
    }

    increaseNumber() {
        this.setState({currentValue: this.state.currentValue + 1});
        this.props.increasedEvent(this.state.currentValue);
    }

    render() {
        return <button onClick={() => this.increaseNumber()}>Increase number</button>
    }
}`}
            </Highlight>

            <p>
                Now everything is ready to intercept that event form the parent component.
                To do that we will add <code>increasedEvent</code> property to <code>SingleEmit</code>
                component definition. Like before with <code>onClick</code> event again we are using 
                JavaScript arrow function to intercept the event and invoke the <code>onIncreased</code>
                method. This time the arrow function will receive the current value of the counter and 
                that value will be passed to the method that will change the state of the counter state property.
            </p>

            <Highlight className="javascript">
                {`export default SingleEmitParent extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            counter: 0,
        }
    }

    onIncreased(value) {
        this.setState({counter: value});
    }
    
    render() {
        return (<div>
            <p>Clicked: {this.state.counter} times.</p>
            <SingleEmit increasedEvent={(event) => this.onIncreased(event)}/>
        </div>)
    }
}`}
            </Highlight>

            <p>
                When the <code>onIncreased()</code> and <code>setState()</code> methods
                are called the value rendered in the template will be updated.
            </p>

           
            {/* https://youtu.be/CmUQ5C35_Oc?t=484 */}
        </div>
    );
  }
}

// vue-app/src/views/Props.vue
<template>
  <div>
    <h1>Component data, methods and properties</h1>

    <p>
        All data within a Vue.js component use reactive data structures.
        Values and DOM element are linked into the Obervable variables due 
        to that while we will be updatating the value of the variable, we 
        will also be updating the DOM element accordingly.
    </p>

    <h2>Component internal data</h2>

    <p>
        Vue component could be treated as an kind of object that has properties
        and methods. When in Json object notation we create a property we  use
        ":" (colon) to separate the property name from the value. The similar 
        approach is used in Vue.js components. There are a few properties that 
        are responsible for the component's behavior. One of them is the <code>data</code>
        method. This is responsible for storing the component's data.
        It should be an function that returns an other objects like in the basic example below.
    </p>
 
    <label>index.html</label>
    <highlightjs language="html" :code="code0html"></highlightjs>

    <label>main.js</label>
    <highlightjs language="javascript" :code="code0js"></highlightjs>

    <p>
      Now using interpolation experssion in HTML template we can access the data stored in the component's data
      and replace that <code>welcomeMessage</code> with the value of that variable. When we use 
      <code>{{"\{\{ \}\}"}}</code> (double curly braces) we are using interpolation expression.
      Specific values are initialized inside that <code>data</code> method and what is important
      is that that all that variables are an instances of Obervable class.
    </p>

    <p>
        That vue.js object has its own lifecycle hooks methods. That allows user to 
        initialize the component's data later when the component is created or mounted.
        One of them is the <code>mounted()</code> hook. This is called when the component is attached to
        the page and rendered the template. More about that is available on the <a href="https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram">Vue.js documentation</a>.
    </p>

    <h2>Passing properties</h2>

    <p>
        How to build a application without component interaction? Fortunately Vue.js provides 
        a way to pass properties to the component. Very similar to the way we define data inside
        component we are defining a properties that are passed to the component. To do that we 
        will use <code>props: [...]</code> property. In a basic example it is a property that 
        has an array of strings. Each of those strings is a property name that could be passed into the 
        component. But there is also a way to define a properties as an object. In that case we have 
        to define the property name as a key and the type of that property as a value.
    </p>

    <label>Props.vue</label>
    <highlightjs language="vue" :code="code1vue"></highlightjs>

    <p>
        Because attributes names in HTML are case-insensitive it doesn't matter if we use
        in our template camleCased prop names or kebab-cased equivalents. Browser will recognize
        then and render the correct value.
    </p>

    <label>Parent.vue</label>
    <highlightjs language="vue" :code="code1parent"></highlightjs>

    <p>
        While using the approach with Single File Components we can import and export the components.
        To use a child component in the parent we have to import it from the origin place and add register
        that component in the <code>components: {...}</code> property of Parent. Now we can use this 
        props to pass the string value to the child component.
    </p>

    <h3>
        Passing Variables
    </h3>

    <p>
        Regarding passing a Static variables we can pass a value that could be any type of data.
        To inform the Vue instance that we want to pass a variable as a value of property we have to use the <code>v-bind</code>
        directive. Directives are powerful special attributes provided by Vue.js that allow us perform 
        reactive behavior on the DOM. Every Vue.js directive is prefixed with <code>v-</code>.
        In the example below we are passing a variable as a value of property using <code>v-bind:welcomeMessage</code>.
    </p>

    <label>Parent.vue</label>
    <highlightjs language="vue" :code="code2parent"></highlightjs>

    <p>
        Some of the Vue.js directives has a shorthand version. In that case we can use just<code>:</code>
        (colon) to indicate that we want to pass a variable as a value of property (<code>:welcomeMessage</code>, 
        so we reduced the <code>v-bind</code> text). We have to remember that we should not change 
        the recived value from parent inside the child component. 

    </p>

     <h2>
        Emmiting Events
    </h2>

    <p>
        Communication from child to parent is much easier than providing a props into the component.
        That works on the same principle like in many other frameworks. We can emit an event from the child
        to the parent that could handle that action. To emit a such event we neet to use 
        the <code>$emit()</code> method from core Vue.js instance. As the argument we pass the name of the event
        and the data that will be transfered. Now only the parent have to listen for that event and handle it.
        To do that we have to use the <code>v-on</code> directive on a specific event name for that component.
        For that directive there is also a shorthand version so v-on: can be replaced by <code>@</code> (at) sign.
    </p>

    <label>SingleEmit.vue</label>
    <highlightjs language="vue" :code="code3child"></highlightjs>

    <p>
        The thing that we can see is the new property for our Vue.js component. It is the 
        <code>methods</code> property. This property is an object that contains all the methods that
        could be used by the component. In child component we have a method called <code>increaseNumber()</code>
        that is responsible for increasing the value of counter inside the child component and the 
        result is emitted to the parent component as an <b>'increased-event'</b> event.
    </p>

    <label>Parent.vue</label>
    <highlightjs language="vue" :code="code3parent"></highlightjs>

    <p>
        Parent component is listening for the event and when it is emitted it will call the method
        <code>onIncreased()</code> that receives the data that was emitted. Recived value is saved 
        to the <code>counter</code> variable inside the parent component and when it is updated 
        the HTML code is immediately updated.
    </p>


    
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Props",

  data() {
    return {
      code0html: `<html>
    <head>
        <title>Vue.js props</title>
        <script type="text/javascript" src="js/vue.js"><script>
    </head>

    <body>
    <div id="app">
        <h1>Hello from {{welcomeMessage}}</h1>
    </div>
    <script type="text/javascript" src="js/main.js"><script>
</body>`,
    code0js: `var app = new Vue({
    el: '#app',
    data() {
        return {
            welcomeMessage: 'Vue.js property!',
        }
    },
})`,
    code1vue: `<template>
    <h1>Hello from {{welcomeMessage}}</h1>
</template>
<script>
export default {
    props: ['welcomeMessage'],
}
<script>
<style>
</style>
`,
    code1parent: `<template>
    <props welcome-message="Vue.js child component"></props>
</template>
<script>
import Props from "./Props.vue";
export default {
    components: {
        Props,
    },
}
<script>
`,
    code2parent: `<template>
    <props v-bind:welcomeMessage="framework"></props>
</template>
<script>
import Props from "./Props.vue";
export default {
    components: {
        Props,
    },
    data() {
        return {
            framework: 'Vue.js',
        }
    }
}
<script>
`,
    code3child: `<template>
    <button @click="increaseNumber()">Increase number</button>
</template>
<script>
export default {
    data() {
        return {
            currentValue: 0,
        }
    },
    methods: {
        increaseNumber() {
            this.currentValue++;
            this.$emit('increased-event', this.currentValue);
        },
    },
}
<script>
<style>
</style>
`, code3parent: `<template>
<div>
    <p>Clicked: {{counter}} times.</p>
    <single-emit v-on:increased-event="onIncreased"></single-emit>
</div>
</template>
<script>
import SingleEmit from "./SingleEmit.vue";
export default {
    components: {
        SingleEmit,
    },
    data() {
        return {
            counter: 0,
        }
    },
    methods: {
        onIncreased(value) {
            this.counter = value;
        },
    },
}
<script>
<style>
</style>
`,
    };
  },
});
</script>
 
<style>
</style>
