// angular/src/app/pages/component-props/props.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'props',
    templateUrl: './props.component.html',
    //   styleUrls: ['./home.component.css']
})
export class PropsComponent {


    code0 = ` import { Component } from '@angular/core';

    @Component({
      selector: 'single-selector',
      template: '<h1>Hello from {{welcomeMessage}}</h1>',
    })
    export class SingleComponent {
      
      welcomeMessage: string;

      constructor() {
          this.welcomeMessage = "Angular Property!";
      }
    }
       `


    code1ts = ` import { Component, Input } from '@angular/core';

 @Component({
   selector: 'single-props-selector',
   template: '<h1>Hello from {{welcomeMessage}}</h1>'
 })
 export class PropsComponent {
    @Input() welcomeMessage: String;

    constructor() { }
 }
    `

    code1html = ` <div>
   <single-props-selector welcomeMessage="Angular Child Component"></single-props-selector>
 </div>
    `

    code2ts = ` import { Component } from '@angular/core';

 @Component({
   selector: 'parent-selector',
   templateUrl: 'parent.component.html'
 })
 export class ParentComponent {
    framework: string = 'Angular';

    constructor() { }
 }
    `
    code2html = ` <div>
    <single-props-selector [welcomeMessage]="framework"></single-props-selector>
  </div>
     `

    code3ts = ` import { Component, Output, EventEmitter } from '@angular/core';

    @Component({
      selector: 'single-emit-selector',
      template: '<button (click)="increaseNumber()">Increase number</button>'
    })
    export class EmitComponent {

        currentValue: number = 0;
        @Output() increasedEvent = new EventEmitter<number>();
   
       constructor() { }

       increaseNumber() {
           this.currentValue++;
           this.increasedEvent.emit(currentValue));
       }
    }
       `
    
    code3html = ` <div>
        <p>Clicked: {{counter}} times.</p>
        <single-emit-selector (increasedEvent)="onIncreased($event)"></single-emit-selector>
      </div>
         `

    code3ts2 = ` import { Component } from '@angular/core';

         @Component({
           selector: 'emit-parent-selector',
           templateUrl: '...'
         })
         export class EmitParentComponent {
             counter: number = 0;
        
            constructor() { }
     
            onIncreased(newValue: number) {
                this.counter = newValue;
            }
         }
            `

    code4 = ` <div>
            <input [(ngModel)]="childName">
            <p>Hello {{childName}}</p>
          </div>
             `

             code4module = ` 
             import { NgModule } from '@angular/core';
             ...
             import {FormsModule} from '@angular/forms';    
             ...
             
             @NgModule({
               imports: [
                 ...
                 FormsModule
               ],
               ...
             })
             export class AppModule { }
              `

}


<div>
    <h1>Component data, methods and properties</h1>
    <p>
        Components in Angular are TypeScript classes so it has all goodies of that.
        The application can use primitive types but it can also use dedicated classed 
        and interfaces that will improve the further scalability. Classes can implement
        some interfaces and classes can extend other classes. So many known object oriented
        programming patterns can be applied to Angular project.
    </p>

    <h2>Component internal data</h2>
    <p>
        Internal data of the component must be defined as class property and can be initialized
        with the constructor. Component class could also defined some methods that could be related
        to that component behavior or other things. In further reading we will see that we can also 
        attach the 'service' classes that could attach additional functionality
        to the component. 
    </p>

    <p>
        But starting from the starch we will just create a SingleComponent class with 
        <code>welcomeMessage</code> property that is a type of <code>string</code> variable. 
        You can see that in this example we initialize that variable using constructor. 
    </p>
    
    <label>single.component.ts</label>
    <pre><code [highlight]="code0" [lineNumbers]="true"></code></pre>

    <p>
        We defined the new property in our SingleComponent class but now we want
        to use it. So there are two ways how to use it on the HTML template.
    </p>

    <ul>
        <li>Text interpolation<br>Embedding the <code>welcomeMessage</code> property into the marked up text.
        It displays the value of that variable in specific place in the template. It has been presented in the
        example above where you can see the double curly braces <code>{{ "{{}\}" }}</code> as the interpolation expression.
        </li>
        <li>Passing as argument<br>Variable can be passed to the child component as an argument.
        It is quite different approach so we are not using the double curly braces but properties passing.
        Don't worry it will be presented in the next section.
        </li>
    </ul>

    <p>
        It is not the only possible way to initialize the component internal data.
        Sometimes it is better to initialize the data inside <code>onInit()</code> method.
        That method is one of the Component Lifecycle Hooks methods. Complete tutorial with all
        lifecycle hooks details is described on the <a href="https://angular.io/guide/lifecycle-hooks">official Angular site</a>.
        Shortly it is a kind of the execution order of the methods inside the component class that initialize 
        specific contents.
    </p>

    <h2>Passing properties</h2>
    <p>
        Even the most advanced component sometime requires an additional data from other place. 
        For example some component should be rendered differently depending on the 
        page where it is located. So to make it possible we can pass some data to the component
        using <code>@Input()</code> decorator. We add that before the property that we want to receive
        form the parent component. (We have to remember about adding the proper import from <code>@angular/core</code>).
        There is an option to give a name for the property that we want to receive adding a property name as an argument 
        to the input decorator function like in this example: <code>@Input('propertyName')</code>. But for the sake of simplicity
        we will continue using the default name of the property to explain exactly what is happening.
    
    </p>

    <label>props.component.ts</label>
    <pre><code [highlight]="code1ts" [lineNumbers]="true"></code></pre>

    <p>
        The variable name is the property name that has to be passed to the component from parent. To pass a simple string
        value we just need to define a attribute like it is done in classic HTML tags. Example was presented below where in 
        <code>parent.component.html</code> we have defined the <code>welcomeMessage</code> attribute with value <code>"Angular Child Component"</code>.
    </p>


    <label>parent.component.html</label>
    <pre><code [highlight]="code1html" [lineNumbers]="true"></code></pre>

    <h3>
        Passing Variables
    </h3>
    <p>
        Sometimes we need to pass more complicated data to the component. It could be an array, map or even another TypeScript object. That is also possible using
        the same approach that we did before but we have to change the way we pass the data in the parent component. If we want to pass an object (in general meaning)
        we need to use the <code>[...]</code> (square braces) around the property name. This improve the readability of the code and the compiler knows that the value 
        provided there is a variable and should be somewhere defined. If it is not defined it will throw an error and user will be informed about that.
    </p>

    <label>parent.component.ts</label>
    <pre><code [highlight]="code2ts" [lineNumbers]="true"></code></pre>


    <label>parent.component.html</label>
    <pre><code [highlight]="code2html" [lineNumbers]="true"></code></pre>

    <p>
        In that way we can communicate with the child components. Now this two components share information stored inside <code>framework</code> variable. 
        There are also some advanced ways to pass data to the child component. Using the getter (<code>@Input() get welcomeMessage(): string "{{'{...}'}}"</code>) 
        we can intercept the provided data and validate, act or modify it. That could be useful if we are creating a component that will be responsible for 
        username validation where we want to make sure that the username will not contain any special characters or white spaces. 
    </p>
    <p>
        From parent component there is no possibility to access child properties or methods. It could be done by creating a <b>Local variable</b> template reference for the child element 
        and when it is done create a reference to it inside the parent component. It could be done by adding a <code>#referenceName</code> attribute to the child component tag. It is the 
        simplest way to do it but it is not recommended. It has that limitation that the local variable reference must be done in the parent component template only. So the parent 
        component class still do not have access to the child component. It could be done using <code>@ViewChild()</code> decorator. That operation inject the child component class into the
        parent and if the variable is defined the parent class will have access to the child component. That is more complex pattern and not commonly used but it is possible.
    </p>

    <h2>
        Emmiting Events
    </h2>
    <p>
        Next step is a communication from child to parent. This time the child component will send information
        to the parent about some event that is just taking place. Using the special <code>@Output()</code> decorator
        the child component define the custom event that when it take place the parent component can interpret 
        this action and do something. The child component has to import the <code>EventEmitter</code> and <code>Ouput</code>
        classes from core Angular library. 
    </p>

    <p>
        In the example below there is a EmitComponent class that has defined the increasedEvent variable that 
        is a kind of EventEmitter class that emits primitive number to parent component when the <code>emit()</code>
        method is invoked. The <code>@Output()</code> decorator is crucial because if it will be missing the 
        parent component will not be aware of the event. Emit method is invoked in that example inside 
        <code>increaseNumber()</code> method body and send an event to parent with latest value of the counter.
    </p>
    
    <label>emit.component.ts</label>
    <pre><code [highlight]="code3ts" [lineNumbers]="true"></code></pre>

    <p>
        From the parent point of view there is something similar that was presented with @Input() decorator.
        When in parent component template the child component is defined it also has a custom attribute
        that is a name of the event defined inside child class. To differentiate the Input and Output the 
        authors of the Angular framework adopted a convention where for event the property is in brackets <code>(...)</code>.
        That makes it easier to find and recognize what is an Input property and  what is the Event handler.
        As it was mentioned before this convention point that the provided value is an object or in that 
        case a method inside parent class that receive an <code>$event</code> object as the argument. 
    </p>


    <label>parent.component.html</label>
    <pre><code [highlight]="code3html" [lineNumbers]="true"></code></pre>

    <label>parent.component.ts</label>
    <pre><code [highlight]="code3ts2" [lineNumbers]="true"></code></pre>

    <p>
        In the example presented above the parent component invokes the <code>onIncreased()</code> method 
        when the child component emits an <code>(increasedEvent)</code> event. Method in parent class 
        receive an argumnet that is an number from child component.
    </p>

    <p>
        That was the simple introduction to the communication between child and parent components. That
        is not complex because we always know what kind of data we are passing or we receive and how it is used.
        More advanced scenarios are described on the <a href="https://angular.io/guide/inputs-outputs">offcial Angular documentation.</a>
    </p>

    <h2>
        2-Way Data Binding
    </h2>

    <p>
        In Angular there is a concept of Two-way data binding that is an another approach to share data
        in application. While using that approach we can listen for events and update values simultaneously
        between child and parent components. It is an combination of the Input and Output pattern. It is possible
        to create it step by step but most of the Angular froms use that approach so it was provided to 
        Angular FormsModule that gives a <code>[(ngModel)]</code> directive. This two-way data binding 
        contents the square brackets with parentheses and combine property binding with event binding.
        Example below shows how to use it with ngModel approach. If you are interested how to create your own
        binding chect <a href="https://angular.io/guide/two-way-binding">this page</a> from official Angular documentation.
    </p>

    <label>form.component.html</label>
    <pre><code [highlight]="code4" [lineNumbers]="true"></code></pre>

    <label>app.module.ts</label>
    <pre><code [highlight]="code4module" [lineNumbers]="true"></code></pre>

</div>

// vue-app/src/views/Props.vue
<template>
  <div>
    <h1>Component data, methods and properties</h1>

    <p>
        All data within a Vue.js component use reactive data structures.
        Values and DOM element are linked into the Obervable variables due 
        to that while we will be updatating the value of the variable, we 
        will also be updating the DOM element accordingly.
    </p>

    <h2>Component internal data</h2>

    <p>
        Vue component could be treated as an kind of object that has properties
        and methods. When in Json object notation we create a property we  use
        ":" (colon) to separate the property name from the value. The similar 
        approach is used in Vue.js components. There are a few properties that 
        are responsible for the component's behavior. One of them is the <code>data</code>
        method. This is responsible for storing the component's data.
        It should be an function that returns an other objects like in the basic example below.
    </p>
 
    <label>index.html</label>
    <highlightjs language="html" :code="code0html"></highlightjs>

    <label>main.js</label>
    <highlightjs language="javascript" :code="code0js"></highlightjs>

    <p>
      Now using interpolation experssion in HTML template we can access the data stored in the component's data
      and replace that <code>welcomeMessage</code> with the value of that variable. When we use 
      <code>{{"\{\{ \}\}"}}</code> (double curly braces) we are using interpolation expression.
      Specific values are initialized inside that <code>data</code> method and what is important
      is that that all that variables are an instances of Obervable class.
    </p>

    <p>
        That vue.js object has its own lifecycle hooks methods. That allows user to 
        initialize the component's data later when the component is created or mounted.
        One of them is the <code>mounted()</code> hook. This is called when the component is attached to
        the page and rendered the template. More about that is available on the <a href="https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram">Vue.js documentation</a>.
    </p>

    <h2>Passing properties</h2>

    <p>
        How to build a application without component interaction? Fortunately Vue.js provides 
        a way to pass properties to the component. Very similar to the way we define data inside
        component we are defining a properties that are passed to the component. To do that we 
        will use <code>props: [...]</code> property. In a basic example it is a property that 
        has an array of strings. Each of those strings is a property name that could be passed into the 
        component. But there is also a way to define a properties as an object. In that case we have 
        to define the property name as a key and the type of that property as a value.
    </p>

    <label>Props.vue</label>
    <highlightjs language="vue" :code="code1vue"></highlightjs>

    <p>
        Because attributes names in HTML are case-insensitive it doesn't matter if we use
        in our template camleCased prop names or kebab-cased equivalents. Browser will recognize
        then and render the correct value.
    </p>

    <label>Parent.vue</label>
    <highlightjs language="vue" :code="code1parent"></highlightjs>

    <p>
        While using the approach with Single File Components we can import and export the components.
        To use a child component in the parent we have to import it from the origin place and add register
        that component in the <code>components: {...}</code> property of Parent. Now we can use this 
        props to pass the string value to the child component.
    </p>

    <h3>
        Passing Variables
    </h3>

    <p>
        Regarding passing a Static variables we can pass a value that could be any type of data.
        To inform the Vue instance that we want to pass a variable as a value of property we have to use the <code>v-bind</code>
        directive. Directives are powerful special attributes provided by Vue.js that allow us perform 
        reactive behavior on the DOM. Every Vue.js directive is prefixed with <code>v-</code>.
        In the example below we are passing a variable as a value of property using <code>v-bind:welcomeMessage</code>.
    </p>

    <label>Parent.vue</label>
    <highlightjs language="vue" :code="code2parent"></highlightjs>

    <p>
        Some of the Vue.js directives has a shorthand version. In that case we can use just<code>:</code>
        (colon) to indicate that we want to pass a variable as a value of property (<code>:welcomeMessage</code>, 
        so we reduced the <code>v-bind</code> text). We have to remember that we should not change 
        the recived value from parent inside the child component. 

    </p>

     <h2>
        Emmiting Events
    </h2>

    <p>
        Communication from child to parent is much easier than providing a props into the component.
        That works on the same principle like in many other frameworks. We can emit an event from the child
        to the parent that could handle that action. To emit a such event we neet to use 
        the <code>$emit()</code> method from core Vue.js instance. As the argument we pass the name of the event
        and the data that will be transfered. Now only the parent have to listen for that event and handle it.
        To do that we have to use the <code>v-on</code> directive on a specific event name for that component.
        For that directive there is also a shorthand version so v-on: can be replaced by <code>@</code> (at) sign.
    </p>

    <label>SingleEmit.vue</label>
    <highlightjs language="vue" :code="code3child"></highlightjs>

    <p>
        The thing that we can see is the new property for our Vue.js component. It is the 
        <code>methods</code> property. This property is an object that contains all the methods that
        could be used by the component. In child component we have a method called <code>increaseNumber()</code>
        that is responsible for increasing the value of counter inside the child component and the 
        result is emitted to the parent component as an <b>'increased-event'</b> event.
    </p>

    <label>Parent.vue</label>
    <highlightjs language="vue" :code="code3parent"></highlightjs>

    <p>
        Parent component is listening for the event and when it is emitted it will call the method
        <code>onIncreased()</code> that receives the data that was emitted. Recived value is saved 
        to the <code>counter</code> variable inside the parent component and when it is updated 
        the HTML code is immediately updated.
    </p>


    
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Props",

  data() {
    return {
      code0html: `<html>
    <head>
        <title>Vue.js props</title>
        <script type="text/javascript" src="js/vue.js"><script>
    </head>

    <body>
    <div id="app">
        <h1>Hello from {{welcomeMessage}}</h1>
    </div>
    <script type="text/javascript" src="js/main.js"><script>
</body>`,
    code0js: `var app = new Vue({
    el: '#app',
    data() {
        return {
            welcomeMessage: 'Vue.js property!',
        }
    },
})`,
    code1vue: `<template>
    <h1>Hello from {{welcomeMessage}}</h1>
</template>
<script>
export default {
    props: ['welcomeMessage'],
}
<script>
<style>
</style>
`,
    code1parent: `<template>
    <props welcome-message="Vue.js child component"></props>
</template>
<script>
import Props from "./Props.vue";
export default {
    components: {
        Props,
    },
}
<script>
`,
    code2parent: `<template>
    <props v-bind:welcomeMessage="framework"></props>
</template>
<script>
import Props from "./Props.vue";
export default {
    components: {
        Props,
    },
    data() {
        return {
            framework: 'Vue.js',
        }
    }
}
<script>
`,
    code3child: `<template>
    <button @click="increaseNumber()">Increase number</button>
</template>
<script>
export default {
    data() {
        return {
            currentValue: 0,
        }
    },
    methods: {
        increaseNumber() {
            this.currentValue++;
            this.$emit('increased-event', this.currentValue);
        },
    },
}
<script>
<style>
</style>
`, code3parent: `<template>
<div>
    <p>Clicked: {{counter}} times.</p>
    <single-emit v-on:increased-event="onIncreased"></single-emit>
</div>
</template>
<script>
import SingleEmit from "./SingleEmit.vue";
export default {
    components: {
        SingleEmit,
    },
    data() {
        return {
            counter: 0,
        }
    },
    methods: {
        onIncreased(value) {
            this.counter = value;
        },
    },
}
<script>
<style>
</style>
`,
    };
  },
});
</script>
 
<style>
</style>
