// angular/src/app/pages/component-slots/slots.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'slots',
    templateUrl: './slots.component.html',
    //   styleUrls: ['./home.component.css']
})
export class SlotsComponent {


    code0child = ` import { Component } from '@angular/core';

    @Component({
      selector: 'child-component',
      template: \`
        <h1>Header of child</h1> 
        <ng-content></ng-content>
        <footer>Footer of child</footer>
        \`,
    })
    export class ChildComponent { }
       `;

    code0parent = `
    <child-component>
        <section>
            <h2>Parent section to be displayed</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </section>
    </child-component>`

    
    code1child = ` import { Component } from '@angular/core';

    @Component({
      selector: 'child-component',
      template: \`
        <ng-content select="[header]"></ng-content>
        <ng-content></ng-content>
        <footer>Footer of child</footer>
        \`,
    })
    export class ChildComponent { }
       `;

    code1parent = `
    <child-component>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <h1 header>Parent header to be rendered first</h1>
    </child-component>`


    
}


<div>
    <h1>Content projection</h1>
    <p>
        One of the most powerful features of modern framework is the Content Projection pattern.
        This approach allows user to build more reusable components and add external content into 
        the Template. That technique allow us to pass HTML elements, other components and 
        everything else to the Template. Child component will render that content in a designated
        place based on the <code>ng-content</code> tag selector. 
    </p>

    <h2>
        Single-slot content projection
    </h2>

    <p>
        As it was explained before we can use <code>ng-content</code> selector to render some 
        specific content into the Template. The example below shows how to use that
        selector to render data from the parent component. The content will be rendered below 
        header selector and above the footer. Each child component will be rendered in the same way.
        So that means that all child components will have a title and a footer but their "body" 
        will be different depending on the data provided by parent.
    </p>
    
    <label>child.component.ts</label>
    <pre><code [highlight]="code0child" [lineNumbers]="true"></code></pre>

    <label>parent.component.html</label>
    <pre><code [highlight]="code0parent" [lineNumbers]="true"></code></pre>

    <p>
        Single slot content projection is very easy to use and it is very powerful tool for developers.
        This element is a placeholder that does not create a real DOM element but it is a reference
        where the data should be rendered. That approach has also a downside. It does not have 
        access to the properties and methods inside the ChildComponent, but in many cases it is
        not a problem.
    </p>

    <h2>
        Multiple-slot content projection
    </h2>

    <p>
        What if we want to add data to multiple specific places in our child template? To solve that 
        issue we can specify a <code>select</code> attribute with specific name to <code>ng-content</code> tag.
        That determines which slot is going to be used by provided data. It works on CSS selector specification
        that determines which content is going into the specific slot. The example below shows how to use
        it.
    </p>

    <label>child.component.ts</label>
    <pre><code [highlight]="code1child" [lineNumbers]="true"></code></pre>

    <label>parent.component.html</label>
    <pre><code [highlight]="code1parent" [lineNumbers]="true"></code></pre>

    <p>
        That is a simple approach to create a multi-slot content projection. But using <code>ng-content</code>
        selector the content of the component is always initialized. There is a way to avoid that by using
        <code>ng-template</code> element that is rendering a data based on the provided condition. 
    </p>

    <!-- <h2>
        Conditional content projection
    </h2>
    <p>
        Instead initializing the content every time we can add some of the logic to the template.
        The tag <code>ng-template</code> allows to render data based on the provided condition 
        and event more than once. 
    </p> -->


</div>

// vue-app/src/views/Slots.vue
<template>
  <div>
    <h1>Content projection</h1>

    <p>
        To build a powerful application that is flexible and extensible, we should 
        provide some outlets for content. Using the <code>slot</code> tag, we can 
        pass not only the properties but also the HTML content to specific the components.
        That pattern enable us to build a flexible application with more reusable components.
    </p>

    <h2>
        Single-slot
    </h2>

    <p>
        To serve content into specific component we have to define the <code>slot</code> tag 
        somewhere in the component template. That content distribution api allows us to 
        compose components in more spohisticatd way. Defining a <code>slot</code> tag inside Child 
        inorm Vue where it should place the content of data provided by parent component. 
        The example below shows how to use that selector to render data from the parent component. The 
        content will be rendered below header selector and above the footer. Each child component 
        will be rendered in the same way. So that means that all child components will have a title 
        and a footer but their "body" will be different depending on the data provided by parent.
        Now everthing within <code>child</code> tag will be rendered inside Child component
        inside the <code>slot</code> tag.
    </p>
 
    <label>Child.vue</label>
    <highlightjs language="vue" :code="code0child"></highlightjs>

    <label>Parent.vue</label>
    <highlightjs language="vue" :code="code0parent"></highlightjs>

    <p>
        Taht content distribution pattern is a powerful tool to build flexible and extensible
        components. This could be used to build a common component that will be displaying 
        different content on the dashboard. This could be also a template for a blog post and so on.
    </p>

    <h2>
        Multiple-slots
    </h2>

    <p>
        Sometimes to compose components we will need more than one slot. It could be easly resolved
        by adding a <code>name</code> attribute to the <code>slot</code> tag. The name attribute
        creates a unique named outlet for the component. If we do not provide that attribute to 
        the slot tag by default it will have "default" name. To use that named outlet we have to
        use the <code>template</code> tag with additional directive <code>v-slot:name</code> where
        name is the name of the slot in child component.
    </p>

    <label>Child.vue</label>
    <highlightjs language="vue" :code="code1child"></highlightjs>

    <label>Parent.vue</label>
    <highlightjs language="vue" :code="code1parent"></highlightjs>

    
    


    
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Slots",

  data() {
    return {
      code0child: `<template>
    <div>
        <h1>Header of child</h1>
        <slot></slot>
        <footer>Footer of child</footer>
    </div>
</template>
<script>
export default { }
<script>`,
    code0parent: `<template>
    <div>
        <child>
            <section>
                <h2>Parent section to be displayed</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </section>
        </child>
    </div>
</template>
<script>
import Child from "./Child.vue";
export default {
    components: {
        Child
    },
}
<script>`,
    code1child: `<template>
    <div>
        <slot name="header"></slot>
        <slot></slot>
        <footer>Footer of child</footer>
    </div>
</template>
<script>
export default { }
<script>`,
    code1parent: `<template>
    <div>
        <child>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <template v-slot:header>
                <h2>Parent section to be displayed</h2>
            </template>
        </child>
    </div>
</template>
<script>
import Child from "./Child.vue";
export default {
    components: {
        Child
    },
}
<script>`,
    };
  },
});
</script>
 
<style>
</style>
