// angular/src/app/pages/component-directives/directives.component.ts
import { Component } from "@angular/core";

@Component({
    selector: 'directives-view',
    templateUrl: './directives.component.html',
})
export class DirectivesComponent {
    
    code1 = `<div [ngClass]="{'selected': true, 'disabled': !isAdmin()}">
    Hello User!
</div>`;

    code2 = `<div class="card card--title" [ngClass]="isValid ? '' : 'card--error'">
    <h2>Login form</h2>
</div>`;

    code3a = `@Component({
    selector: 'app-input-label',
    templateUrl: './input-label.component.html',
})
export class InputLabelComponent {
    
    @Input() required: string;
    @Input() disabled: string;

    inputStyles = {
        'font-weight': this.required ? 'bold' : 'normal',
        'color': this.disabled ? '#999' : '#000'
    };
}`;

    code3b = `<span [ngStyle]="inputStyles"> Label text </span>`;

    code4 = `<span *ngIf="basketItems > 0"> You have {{basketItem}} items in your basket.</span>`;

    code5 = `<div *ngFor="let item in basketProducts">{{item.name}}</div>`;

    code5b = `<div *ngFor="let item in basketProducts; let i=index">
    {{i+1}}: {{item.name}}
</div>`;

    code5c = `trackItems(index: number, item: any): number {return item.id;}`

    code5d = `<div *ngFor="let item in basketProducts; trackBy: trackItems">
    {{i+1}}: {{item.name}}
</div>`;

    code6 = `<div [ngSwitch]="user.gender">
    <div *ngSwitchCase="'male'">Special offer for military stuff!</div>
    <div *ngSwitchCase="'female'">We are starting a winter discount!</div>
    <div *ngSwitchDefault>Welcome to our shop!</div>
</div>`;

    code4ext = `<ng-template [ngIf]="basketItems > 0">
    <span> You have {{basketItem}} items in your basket.</span>
</ng-template>`;

    

    



    
};

    
<div>
    <h1>Angular directives</h1>

    <p>
        Directives in Angular are a way to extend the functionality of your applicationts by giving
        them a new syntax. That are classes that add a additional behavior to the HTML elements.
        Each directive has its own name and the type where it can be used. The basic Angular component
        is actually a directive so base on that we can say that the directives are the most important
        part of the Angular framework. I've mentioned that the Angular application is built on the
        component but I should say that the Angular application in general is built on the directives.
    </p>
    <p>
        In Angular there are three types of directives:
    </p>
    <ol>
        <li>
            <b>Components</b> - That are just a directives with templates.
        </li>
        <li>
            <b>Attribute directives</b> - That directives manipulate the DOM by changing or listening its behavior and appearance.
            It may change the behavior of the element, attribute, property, component or another directive.
        </li>
        <li>
            <b>Structural directives</b> - That directives change the DOM layout by adding, hiding or removing the
            elements from the DOM. They can change the HTML structure of the page.
        </li>
    </ol>

    <h2>Angular build-in attribute directives</h2>
    <p>
        Using the existing directives is very easy because everything you need it to add 
        a specific attribute to the HTML element. Many Angular Modules may have their own
        directives that are built-in to the specific module like <code>router-link</code> from 
        the RouterModule. But in this example I want to present the most common directives.
    </p>

    <h3>NgClass</h3>

    <p>
        The NgClass directive allows you to add and remove CSS classes dynamically to specific HTML element.
        It takes a list of CSS classes and adds them to the element if the expression evaluates to true,
        and removes them when the expression evaluates to false. 
    </p>

    <label>directive.component.html</label>
    <pre><code [highlight]="code1" [lineNumbers]="true"></code></pre>

    <p>
        In that case we attached the <code>ngClass</code> attribute directive to the <code>div</code> element.
        This directive will receive a object with the CSS classes that we want to add or remove depending on the 
        state of our component. The <code>selected</code> class will be added always because the expression is always true,
        but the <code>disabled</code> class will be added only if the <code>isAdmin()</code> method returns false.
        Because we pass the object to the directive we must add the square brackets <code>[]</code> around directive name
        (it's working in the same way how it was done with Input/Output syntax).
    </p>

    <p>
        Because it can handle the object reference from our component we attach to this directive any property that
        we want. It may be a public property or public method from our component. Each key of the object will be treated 
        as the CSS class name. We can also combine that directive with simple <code>class</code> attribute.
        Using this approach we can add static CSS classes to the element and extend it with dynamic classes
        that will be based on the component state.
    </p>

    <label>login.component.html</label>
    <pre><code [highlight]="code2" [lineNumbers]="true"></code></pre>

    <p>
        In this example we can see that the <code>div</code> element will always have the <code>card</code> and <code>card--title</code> classes.
        But if the isValid property is false this ngClass directive will add the <code>card--error</code> class to this HTML element.
        As you can see in this example the argument that we pass to the directive is an string that represents the CSS class name that should be added or removed.
    </p>

    <h3>NgStyle</h3>
    <p>
        The same syntax works for the NgStyle directive. This one is responsible for manipulating the 
        inline styles based on the provided expression.
    </p>

    <label>input-label.component.ts</label>
    <pre><code [highlight]="code3a" [lineNumbers]="true"></code></pre>

    <label>input-label.component.html</label>
    <pre><code [highlight]="code3b" [lineNumbers]="true"></code></pre>

    <p>
        In this example depending on the <code>@Input</code> properties 
        we can change the style of the input label. If we pass the <code>required</code> property
        the Label text will be changed to bold. In <code>inputStyles</code> class property we manipulate the 
        CSS selectors and base on the state of the component we can change them to specific value.
        Easy and understandable. Isn't it?
    </p>

    <h2>Build-in structural directives</h2>

    <p>
        Structural directives allows us to change the DOM structure by adding, removing or 
        manipulating the elements where that directive is attached. The three most popular 
        structural directives are: <code>NgIf</code>, <code>NgFor</code> and <code>NgSwitch</code>.
        Each works in a similar way how their names suggest. It is most popular statements like 
        <code>if</code>, <code>for loop</code>, and <code>switch</code> that are used in the JS code
        but this time they have this <code>Ng</code> prefix. Because structural directives 
        can modify DOM nodes, apply only one structural directive per element.
    </p>

    <h3>NgIf</h3>
    <p>
        Conditional rendering. That directive is responsible for creating or removing the other elements
        from the host element. When the expression is <code>false</code> Angular removes that element 
        from the DOM and disposes components that are attached to that element which can free up memory 
        and resources.
    </p>

    <p>
        This directive is a nice guard against the <code>null</code> value. For example if we want to 
        display the <code>name</code> property of the <code>user</code> object we can use the <code>ngIf</code>
        to check if the <code>user</code> object is not <code>null</code>. In that way we can be sure that 
        the Angular will not generate an error when we try to access the <code>name</code> property.
    </p>

    <label>basket.component.html</label>
    <pre><code [highlight]="code4" [lineNumbers]="true"></code></pre>

    <p>
        Here we can see that the amount of items in basket is displayed only when there is more than 0 items.
    </p>

    <h3>NgFor</h3>
    <p>
        This is the a directive that is responsible for iterating over the array of objects. It 
        will present the list of items based on the host HTML block. This host block will be the 
        definition how Angular should present that list. This directive requires a string
        instruction that define the single item from the specified array. Like 
        in this example <code>ngFor="let item of items"</code>. We create a variable <code>item</code>
        from the <code>items</code> array. 
    </p>

    <label>orders.component.html</label>
    <pre><code [highlight]="code5" [lineNumbers]="true"></code></pre>

    <p>
        In this case we want to present the list of orders and each order will be represented by a <code>div</code> element
        that innerText will be the name property of the order.
    </p>

    <p>
        The <code>ngFor</code> directive context may return the zero-based index of the item in each iteration.
        So we can get the <code>index</code> of the item variable that we used in the template. 
        To do that we can add a semicolon after the array name and add the <code>let i=index</code> to get the 
        index of the item in variable named <code>i</code>.
    </p>

    <label>orders.component.html</label>
    <pre><code [highlight]="code5b" [lineNumbers]="true"></code></pre>

    <p>
        Sometimes we want to render a dynamic list of items that can be changed when 
        the component receives new data. In this case every change in the data array will cause
        the whole list to be re-rendered. To prevent this we can use the <code>trackBy</code>
        property that is responsible for tracking changes in the data array. To do that we have to 
        create a function in the component definition that will return the value that <code>ngFor</code>
        should track. 
    </p>

    <label>orders.component.ts</label>
    <pre><code [highlight]="code5c" [lineNumbers]="true"></code></pre>

    <label>orders.component.html</label>
    <pre><code [highlight]="code5d" [lineNumbers]="true"></code></pre>

    <p>
        To track by the property of the object that we use in our loop we have to defined a 
        dedicated method in the component class. In this case we have named it <code>trackItems</code>.
        If we want to track base on the index returned form the directive we can reduce that method to 
        only one argument. 
    </p>

    <h3>NgSwitch</h3>

    <p>
        Like in JavaScript also here in Angular we can use the <code>switch</code> statement that 
        displays one element from among all defined elements based on the condition. This directive 
        requires at least two elements host element for the <code>ngSwitch</code> and one or more
        elements that will be displayed based on the condition.
    </p>

    <label>shop.component.html</label>
    <pre><code [highlight]="code6" [lineNumbers]="true"></code></pre>

    <h3>Structural directives shorthand</h3>

    <p>
        As you noticed the each structural directive was presented in a shorthand version. 
        This asterisk <code>*</code> symbol is used to indicate that we want to apply the directive
        which Angular later interprets in longer form. Angular transforms the asterisk into 
        and <code>ng-template</code> tag that surrounds the host element. So in our case with 
        basket items in <code ngNonBindable>*ngIf</code> example the longer version of the same directive is:
    </p>

    <label>basket.component.html</label>
    <pre><code [highlight]="code4ext" [lineNumbers]="true"></code></pre>

    <p>
        As we can see it is doing the same thing as the <code>ngIf</code> directive with the 
        asterisk but it is much longer. Now we can see that the <code>ngIf</code> directive is
        surrounded by the square brackets <code>[]</code> like it was done with the attribute
        directives. So now you can see that this is the same mechanism that Angular uses to
        apply the directive.
    </p>

    <h2>Custom directives</h2>
    <p>
        Of course we can create our own directives. Custom directive can do anything that we want
        on a host element. To do that we have to create a directive class in our application.
        The step by step guide is available on the official <a href="https://angular.io/guide/attribute-directives#building-an-attribute-directive">Angular documentation</a>.
    </p>

    <!-- https://angular.io/guide/built-in-directives -->




    

</div>

// react-app/src/views/Directives.tsx
import * as React from 'react';
import Highlight from 'react-highlight'


interface Props { };
interface State {
    ren: number[]
};

export default class Directives extends React.Component<Props, State> {

    state: State = {
        ren: [11, 22, 33],
    }


    render() {
        return (
            <div>
                <h1>Directives? What is it?</h1>

                <p>
                    If you are looking for directives in the React application you may find it difficult.
                </p>

                <p>
                    React keep the state of the Virtual DOM so it is responsible for rendering and generating
                    the DOM elementns. This is the fundamental principle how the React works. There is no
                    reason to use something you may known from the Angular or Vue.js framework like
                    directives that are attached to HTML tags because there is no DOM elements where
                    that directive could be attached. When you are providing a attribute for
                    your React component it is treated as property that is passed to the component.
                </p>

                <h2>Dynamic CSS classes</h2>

                <p>
                    Ok so we know that we do not have any directives available in the React.js framework. But
                    how to handle the same issues that Angular and Vue.js handle with directives? The answer
                    is "use JavaScript". React take advantage of the JavaScript and we can use it to create
                    a functions that will provide the expected behavior.
                </p>

                <Highlight className="javascript">
                    {`render() {
    return (
        <div className={\`selected \${this.isAdmin() ? "" : "disabled"}\`}>
            Hello User!
        </div>
    )
}`}

                </Highlight>

                <p>
                    When the state of a component changes, React performs a re-render and in that
                    moment we pass the respective CSS classes to our div.
                </p>

                <h2>Dynamic Inline-styling</h2>

                <p>
                    This time we will also bind the expression to the style attribute. Because
                    everything in React is an JavaScript we can easily assing specific object to that
                    attribute using the assignment operator.
                </p>

                <Highlight className="javascript">
                    {`export default InputLabel extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            inputStyles: {
                color: this.props.disabled ? "#999" : "#000",
                font-weight: this.props.required ? "bold" : "normal"
            }
        }
    }
                
    render() {
        return (
            <span style={this.state.inputStyles}>Label text</span>
        )
    }
}`}

                </Highlight>

                <p>
                    In this example depending on the provided properties we can change the style of
                    the input label. If we pass the required property the "Label text" will be
                    bolded. In inputStyles object we manipulate the CSS selectors and base on the
                    state of the component we can change them to specific value. In JSX we only need to
                    bind the style attribute with the reference of that object. We have to remember that
                    the "style" behave like a property in React.js instead of an classic attribute.
                </p>

                <h2>Conditional rendering</h2>

                <p>
                    Again we have to use the clear JavaScript to render a specific HTML code but this
                    time we can use the "if" statement. If the condition is true we will render the
                    <code>span</code> block with the basket size information. Otherwise this block will
                    return null that will not be rendered.
                </p>

                <Highlight className="javascript">
                    {`render() {
    return (
        {this.state.basketItems > 0 && <span>You have {this.state.basketItems} items in your basket.</span>}
    )
}`}

                </Highlight>

                <p>
                    Here we can see that the amount of items in basket is displayed only when there is more than 0 items.
                </p>

                <p>
                    In JSX we can use ternary operator to show two code blocks depending on the condition result.
                </p>

                <Highlight className="javascript">
                    {`render() {
    return (
        {this.state.basketItems > 0
            ? <span>You have {this.state.basketItems} items in your basket.</span>
            : <span>Your basket is empty.</span>
        }
    )
}`}

                </Highlight>

                <h2>Rendering the list</h2>

                <p>
                    Finally sometimes we need to render a list of items. Again in this case we can't
                    use directly a "for" directive but we can think of it as a JavaScript code and
                    we can use the "map" function to iterate over the list.
                </p>

                <Highlight className="javascript">
                    {`render() {
    return (
        {this.state.basketProducts.map((item) => <div>{item.name}</div>)}
    )
}`}
                </Highlight>

                <p>
                    In this case we want to present the list of orders and each order will be represented by a
                    <code>div</code> element that innerText will be the name property of the order.
                </p>
                <p>
                    Using map we can return the zero-based index of the item in the list.
                    So we can get the index of the item variable that we used in the JSX.
                    To do that we can extract the second argument form map method and then use it as a variable.
                </p>

                <Highlight className="javascript">
                    {`render() {
    return (
        {this.state.basketProducts.map((item, i) => <div>{i+1}: {item.name}</div>)}
    )
}`}
                </Highlight>

                <p>
                    Sometimes we want to render a dynamic list of items that can be changed when the component
                    receives new data. In this case every change in the data array will cause the whole list to
                    be re-rendered. To prevent this we can use the key property that is responsible for tracking
                    changes in the data array. To do that we only have to bind the key attribute with proper value.
                    In this case we want to use the id of the item as a key.
                </p>

                <Highlight className="javascript">
                    {`render() {
    return (
        {this.state.basketProducts.map((item, i) => <div key={item.id}>{i+1}: {item.name}</div>)}
    )
}`}
                </Highlight>

                <p>
                    In React this list rendering syntax within JSX may be too long and can be hard
                    to read. So if we want to provide more complex list rendering we can create
                    a specific function or variable that will be responsible for rendering the list
                    in a clear way.
                </p>

                <Highlight className="javascript">
                    {`render() {
    const itemsList = this.state.basketProducts.map((item, i) => 
        <div key={item.id}>{i+1}: {item.name}</div>);
    return (
        <header>{itemsList}</header>
    );
}`}
                </Highlight>

            </div>
        );
    }
}
