// react-app/src/views/Lifecycle.tsx
import Highlight from "react-highlight";

const Lifecycle: React.FC = () => {
    return (
        <div>
            <h1>Components Lifecycle hooks</h1>

            <p>
                Hook is a common name for Component Lifecycle Event that is emitted
                during creation, update or deletion of specific component. They are very useful
                for fetching data on mount or for cleaning up intervals just before unmounting.
                In React 16.8 added support for Create and Update hook in Functional Components.
                Before that version developers must use Class Components to implement them.
            </p>

            <h2>Mounting</h2>

            <p>
                This lifecycle method runs only once when the component is mounted and rendered
                to the DOM. This hook can be useful for fetching initial data or for setting up.
            </p>

            <Highlight className="javascript">
                {`// Class Component Example
class PhotoGallery extends React.Component {
    ...

    componentDidMount() {
        ... 
        this.setState({photos: receivedPhotos});
    }

    ...
}`}
            </Highlight>

            <p>
                In class component this is quite simple because we just need to write a new
                function called <code>componentDidMount</code> and React just know that
                this method should be called right after mounted.
            </p>

            <Highlight className="javascript">
                {`// Function Component Example
const PhotoGallery = () => {
    ...
    useEffect(() => {
        ...
        setPhotos(receivedPhotos);

    }, []);

    ...
}`}
            </Highlight>

            <p>
                On the other hand in functional component we have to use <code>useEffect</code> method.
                But that might be a little bit tricky because we have to pass an empty array as a second argument.
                The first one is a callback function that will be called after the component is mounted.
                And the second parameter is an array of variables that should be watched for changes.
                So if we pass an empty array, the callback function will be called only once when the component is mounted.
            </p>

            <h2>Updating</h2>

            <p>
                Update hook is called just after any update inside the component. Too much updates
                can cause the performance issues. So it is very important to use it carefully.
            </p>

            <Highlight className="javascript">
                {`// Class Component Example
class PhotoGallery extends React.Component {
    ...

    componentDidUpdate(prevProps, prevState) {
        // This part is called every time anything in the component is updated
        ... 
        if(this.props.galleryId !== prevProps.galleryId) {
            // This part is called only when the galleryId is changed
        }
    }

    ...
}`}
            </Highlight>

            <p>
                Class components has just one method called <code>componentDidUpdate</code> that is called
                after the component is updated. The method receives two parameters: previous props and previous state.
                So we can check if the specific property or state value has changed and react to that event. For example
                we can fetch a new photo list every time the GalleryID property has changed.
            </p>

            <Highlight className="javascript">
                {`// Function Component Example
const PhotoGallery = ({galleryId}) => {
    ...

    useEffect(() => {
        // This part is called every time anything in the component is updated
    })

    useEffect(() => {
        // This part is called only when the galleryId is changed
    }, [galleryId])

    ...
}`}
            </Highlight>

            <p>
                Function components require an <code>useEffect</code> method from "React". It is the
                same method that we used to implement a "Mounted" hook in a functional component.
                This time the first example present a situation when we want take action every time
                anything in the component is updated. The second example present how to do something
                only when the specific property has changed. <br />
                As we can see this <code>useEffect</code> method is more simple and make code more readable.
                But it has a drawback. We can not access to the previous props or state value.
            </p>

            <h2>Deletion</h2>

            <p>
                Last but not least, the deletion lifecycle method. This method is called just before
                component removal or unmounting. It is called only once per component lifecycle.
            </p>

            <Highlight className="javascript">
                {`// Class Component Example
class PhotoGallery extends React.Component {
...

    componentWillUnmount() {
        ... 
        clearInterval(this.state.refreshInterval);
    }

    ...
}`}
            </Highlight>

            <p>
                <code>componentWillUnmount</code> method is responsible for cleaning up the component just before 
                it will be deleted. This time the React developer team do not provided any additional method to handle
                that hook inside Functional Components. 
            </p>


        </div>
    )

}

export default Lifecycle;

// angular/src/app/pages/component-lifecycle/lifecycle.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'lifecycle',
    templateUrl: './lifecycle.component.html',
})
export class LifecycleComponent {


    code0 = `@Component({
  selector: 'photo-gallery',
  template: 'photo-gallery.component.html',
})
export class PhotoGalleryComponent {
  ...

  constructor() {
      this.galleryId = 0;
      this.photos = [];
  }
  ...
}`

    code1 = `@Component({
    selector: 'photo-gallery',
    template: 'photo-gallery.component.html',
  })
  export class PhotoGalleryComponent implement OnInit {
    ...
  
    ngOnInit() {
        this.photos = fetchPhotos(this.galleryId);
    }
    ...
  }`

    code2 = `@Component({
    selector: 'photo-gallery',
    template: 'photo-gallery.component.html',
  })
  export class PhotoGalleryComponent implements DoCheck {
    ...
  
    ngDoCheck() {
        // This part is called every time anything in the component is updated

        if(this.galleryId !== this.oldGalleryId) {

            // This part is called only when the galleryId is changed
            this.photos = fetchPhotos(this.galleryId);
            this.oldGalleryId = this.galleryId;
        }
    }
    ...
  }`

    code3 = `@Component({
    selector: 'photo-gallery',
    template: 'photo-gallery.component.html',
  })
  export class PhotoGalleryComponent implements OnDestroy {
    ...
  
    ngOnDestroy() {
        ...
        clearInterval(this.refreshInterval);
    }
    ...
  }`
}


<div>
    <h1>Component Lifecycle hooks</h1>
    <p>
        Every component instance instance in Angular has its own lifecycle. The lifecycle is a sequence of events
        that occur during the life of a component instance. Mostly those hooks are emitted during creation, update
        or deletion of the component instance. Angular checks to see when data-bound properties change, and updates
        both the view and the component instance as needed. The lifecycle ends when Angular destroys the component
        instance and removes template from the DOM. This events are very useful for fetching data on mount or for
        cleaning up intervals just before unmounting.
    </p>

    <h2>Component creation (Constructor)</h2>

    <p>
        Component constructor is not directly a Lifecycle Hook but developer should know that it is called before
        all the other lifecycle hooks. It is used to inject dependencies and initialize the component. Constructor
        should do no more than setting up the initial local variables to simple values.
    </p>

    <label>photo-gallery.component.ts</label>
    <pre><code [highlight]="code0" [lineNumbers]="true"></code></pre>

    <h2>Input properties initialization or change</h2>

    <p>
        Then when the constructor has been called Angular is checking the <code>@Input()</code> properties and if
        any of them has changed, it will call the <code>ngOnChanges()</code> method. Using that hook we can respond
        for every data-bound input change. This operation may happen frequently so performing complex operations
        may impact the performance.
    </p>

    <h2>Mounting</h2>

    <p>
        Lifecycle hook interfaces are defined in the Angular core library. So we can implement them in our components
        by importing them from the core library. Each hook method name is prefixed with <code>ng</code>.
    </p>

    <p>
        To initialize the component we need to call the <code>ngOnInit()</code> method. It is called only once
        after the first <code>ngOnChanges()</code> call to perform complex initialization outside of the constructor.
        This is the best place to fetch data from the server.
    </p>

    <label>photo-gallery.component.ts</label>
    <pre><code [highlight]="code1" [lineNumbers]="true"></code></pre>

    <h2>Updating</h2>

    <p>
        Now we are moving into the most complex part of Angular component lifecycle. <code>ngDoCheck()</code> hook is
        responsible for detection and reacting every change in the component that Angular can't find out by itself. In
        this
        hook we can implement our own change check. While this hook can detect every custom parameter change it is very
        expensive and it is very important to use it carefully. This hook is called with enormous frequency after
        <b>every</b>
        change detection cycle. implementation for this hook must be lightweight to avoid performance issues.
    </p>

    <label>photo-gallery.component.ts</label>
    <pre><code [highlight]="code2" [lineNumbers]="true"></code></pre>

    <p>
        <code>ngDoCheck</code> and <code>ngOnChanges</code> should not be implemented in the same component.
    </p>

    <h2>Deletion</h2>

    <p>
        This method will be invoked just before Angular destroys the component. It is called only once per component
        lifecycle.
        Use this hook to unsubscribe observables and detach event handlers to avoid memory leaks.
    </p>

    <label>photo-gallery.component.ts</label>
    <pre><code [highlight]="code3" [lineNumbers]="true"></code></pre>

    <h2>Hooks for component children</h2>

    <p>
        Besides the classic parent component lifecycle hooks, Angular also provides hooks for child components in the
        parent component.
        This hooks are called only for components that has children content.
    </p>

    <h3>
        ngAfterContentInit()
    </h3>

    <p>
        This one is invoked after Angular perform content projection into the component view.

    </p>

    <h3>
        ngAfterContentChecked()
    </h3>

    <p>
        Invoked every time there was a change in the content of given component.
    </p>

    <h3>
        ngAfterViewInit()
    </h3>

    <p>
        Invoked when the component view has been fully initialized with all parent and child content.
    </p>

    <h3>
        ngAfterViewChecked()
    </h3>

    <p>
        Invoked each time the view of the given component has been checked by the change detection mechanism of Angular.
    </p>


</div>
