// angular/src/app/shared/layout/navbar/navbar.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {
    
}


<nav>
    <div>
        <ul>
            <li routerLink="/"><span>Home</span></li>
            <li routerLink="/project-initialization"><span>Project initialization</span></li>
            <li routerLink="/simple-component"><span>Component Example</span></li>
            <li routerLink="/props-component"><span>Component Parameters</span></li>
            <li routerLink="/lifecycle-component"><span>Component Lifecycle</span></li>
            <li routerLink="/slots-component"><span>Component Projection</span></li>
            <li routerLink="/extend-component"><span>Extending Components</span></li>
            <li routerLink="/services-component"><span>Services</span></li>
            <li routerLink="/directives-component"><span>Directives</span></li>
            <li routerLink="/store-component"><span>Store concept</span></li>
        </ul>
    </div>
</nav>

// react-app/src/layout/Navbar.tsx
import * as React from 'react';
import './Navbar.css';
import {
    Link
  } from "react-router-dom";

interface Props {
    // framework: String;
};

interface State {
//   welcomeMessage: String;
};

export default class Navbar extends React.Component<Props, State> {
  state: State = {
    // welcomeMessage: 'Hello from '
  };

  render () {
    return (
      <div>
          <nav>
              <div>
                  <ul>
                      <li><Link to="/">Home</Link></li>
                      <li><Link to="/project-initialization">Project initialization</Link></li>
                      <li><Link to="/simple-component">Component Example</Link></li>
                      <li><Link to="/props-component">Component Parameters</Link></li>
                      <li><Link to="/lifecycle-component">Component Lifecycle</Link></li>
                      <li><Link to="/slots-component">Component Projection</Link></li>
                      <li><Link to="/extend-component">Extending components</Link></li>
                      <li><Link to="/services">Service</Link></li>
                      <li><Link to="/directives-component">Directives</Link></li>
                      <li><Link to="/store-component">Store concept</Link></li>
                  </ul>
              </div>
          </nav>
      </div>
    );
  }
}
