// angular/src/app/shared/layout/topbar/topbar.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-topbar',
  templateUrl: './topbar.component.html',
  styleUrls: ['./topbar.component.css']
})
export class TopbarComponent {
    
}


<div class="topbar">
<h1>Angular Page</h1>
<div class="lang-selector">
    <select (change)="changeLanguage($event.target.value)">
        <option value="en">English</option>
        <option value="pl">Polski</option>
    </select>
</div>
</div>

// react-app/src/layout/Topbar.tsx
import * as React from 'react';
import './Topbar.css';
import { withTranslation, WithTranslation } from 'react-i18next'

interface Props {};
interface State {};

 class Topbar extends React.Component<Props & WithTranslation, State> {

  changeLanguageHandler({target}: React.ChangeEvent<HTMLSelectElement>) {
    this.props.i18n.changeLanguage(target.value)
  }
 
  render () {
    return (
        <div className="topbar">
            <h1>React page</h1>
            <div className='language-selector'>
              <select onChange={(e) => this.changeLanguageHandler(e)}>
                <option value={"pl"}>Polski</option>
                <option value={"en"}>English</option>
              </select>
            </div>
        </div>
    );
  }
}

export default withTranslation()(Topbar)
