// vue-app/src/views/Basic.vue
<template>
  <div>
    <h1>Component Introduction</h1>

    <p>
      <span class="quote">
        "Vue is designed from the ground up to be incrementally adoptable".
      </span>
      <span class="quote--author">
        <a href="https://vuejs.org/v2/guide/">Vue.js Guide.</a>
      </span>
      As the author of the Vue.js framework guide mentions, Vue goal is to
      provide a simple, flexible and easy to maintain framework. It is mostly
      powerful for building single page applications and is open to cooperate
      with other libraries.
    </p>
    <p>
      Vue.js is very similar to React.js in terms of the way it render data on
      the screen. But it is also share the same approach with template section
      that is available in Angular. So to create a web application we will start
      from creating a component that define a custom elements that can be
      reused. Like in React this framework use JavaScript to render the data by
      a virtual DOM. Every data and the DOM elements are reactive and is an
      Vue.js instance. The app is attached to single DOM element on the page and
      rest is done by scripts.
    </p>

    <p>
      Creation of a component is not such a simple task. Why? Because we can do
      it in a many ways. For the begining we will attach the Vue.js component
      into the existing HTML page. To do that we will use the "vue.js" library
      added to the HTML by <code>&lt;script&gt;</code> tag. Vue.js component is
      a JavaScript function that could be called inside the HTML file.
    </p>

    <label>index.html</label>
    <highlightjs language="html" :code="code0"></highlightjs>

    <p>
      When the new Vue instance is called it search for element with ID provided in
      <code>el</code> parameter. In this case we will use <code>#vue_custom_application</code>.
      That is the declarative rendering example. The template of that application is also
      defined inside clear HTML file but it also could be a part of the component.
    </p>

    <h2>Single File Component</h2>
    <p>
      Vue.js is a very flexible framework that can be used for small projects but could be also 
      a base for the bigger projects. So to maintain the code base we can create a <code>*.vue</code> files 
      that define specific Vue.js components. This approach require a build tool like Webpack that 
      will compile the code and prepare standalone application. 
    </p>

    <label>SingleComponentSelector.vue</label>
    <highlightjs language="vue" :code="code1"></highlightjs>

    <p>
      Each Single File Component is a combination of template, script and style sections.
      As I mentioned before Vue.js is a very flexible framework so you can use different 
      languages for each of this section. For purpouse of this project I will use default JavaScript 
      to compare it with the Angular and React.js approach. 
    </p>
    <ul>
      <li>
        <code>template</code> - defines the HTML template that will be rendered
      </li>
      <li>
        <code>script</code> - defines the JavaScript or other language Vue component
        that can contain data, methods and many more things to provide some specific functionality.
      </li>
      <li>
        <code>style</code> - that defines the CSS definitions for the Vue components or just for 
        a single component if it is <code>scoped</code>.
      </li>
    </ul>

    <h2>Basic Vue.js Component</h2>
    <p>
      For smaller projects you will see the approach with components defined inside JavaScript files.
      Component defined with <code>Vue.component()</code> method has its own tag that is used to 
      place that component on the page. Then the framework will create a new instance of that component.
    </p>

    <label>component.js</label>
    <highlightjs language="javascript" :code="code2js"></highlightjs>
    
    <h2>Component usage</h2>

    <p>To use that component defined before we have to use its tag inside Vue instance.</p>

    <label>index.html</label>
    <highlightjs language="html" :code="code2html"></highlightjs>

    <p>
      The <code>basic-component</code> component was globaly registered to Vue instance.
      That components could be reused in other places. 
    </p>
    
    <h2>Root Component</h2>
    <p>
      When project is bigger and use <code>vue-cli</code> to create a Vue.js instance 
      we need a root component that will be the entry point of the application. Single 
      File Components require that definition to be able to provide specific import and 
      export mechanism. Inside <code>public/index.html</code> we can find the 
      <code>&lt;div id="app"&gt;</code> tag that will be used to render the root 
      component defined in <code>App.vue</code>. But the <code>main.js</code> file will contain 
      the the JavaScript initialization code that is loaded by the
      index page and attaching that <code>App</code> component to that <code>div</code> with this <code>#app</code> ID.

    </p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface State {
  code0: string;
  code1: string;
  code2html: string;
  code2js: string;
}

export default defineComponent({
  name: "Basic",

  props: {
    framework: String,
  },


  data: (): State => {
    return {
      code0: `<html>
  <head> 
    <title>Vue.js embedded</title>
    <script type="text/javascript" src="js/vue.js"><script> 
  </head>

  <body>
        
    <div id="vue_custom_application">
      <h1>Welcome in Vue.js!</h1>
    </div>

    <script>
      var vm = new Vue({
        el: "#vue_custom_application",
      });
    <script>

  </body>
</html>`,
    code1:`<template>
<h1>Hello from Vue.js SFC</h1>
</template>
<script>
export default {
  name: "SingleComponentSelector",
};
<script>
<style>
h1 {
  font-weight: bold;
}
</style>
    `,
    code2html:`<html>
  <head>
    <title>Vue.js component</title>
    <script type="text/javascript" src="js/vue.js"><script>
  </head>

  <body>
    <h2>Vue component</h2>
    <div id="vue_main">
      <basic-component></basic-component>
    </div>
  </body>
  <script type="text/javascript" src="js/component.js"><script>

</html>`,
    code2js:`Vue.component('basic-component', {
  template: '<h1>Hello from Vue.js component</h1>',
});

var vm = new Vue({
  el: '#vue_main'
});
`,

    };
  },
});
</script>
 
<style>
</style>

// angular/src/app/pages/component-basic/basic.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'basic',
  templateUrl: './basic.component.html',
//   styleUrls: ['./home.component.css']
})
export class BasicComponent {
    @Input() framework: String = "";
    welcomeMessage: string = 'Hello from ';

    code1 = ` import { Component } from '@angular/core';

 @Component({
   selector: 'single-component-selector',
   template: '<h1>Hello from Angular SFC</h1>',
   styles: ['h1 {font-weight: bold;}']
 })
 export class SingleComponent {
   constructor() { }
 }
    `

    code2 = ` import { Component } from '@angular/core';

 @Component({
   selector: 'basic-component-selector',
   templateUrl: './basic.component.html', //templateUrl instead of template
   styleUrls: ['./basic.component.css']  //styleUrls instead of styles
 })
 export class BasicComponent {
   constructor() { }
 }
    `

    code3 = ` <div>
   <h2>Angular component</h2>
   <!-- Below is the BasicComponent usage example -->
   <basic-component-selector></basic-component-selector>
 </div>
       `

    code4 = ` /* ... */
 import { BasicComponent } from './basic-component/basic.component'
 
 @NgModule({
   declatations: [
     /* ... */
     BasicComponent,
    ],
    /* ... */
 })
 export class AppModule { } 
`
      
    
    
}


<div>
    <h1>Component Introduction</h1>

    <p>
        Angular is a component-based framework that is well designed to build scalable web applications.
        The smallest block from which application is built is the component. It is a TypeScript class with
        <code>@Component()</code> decorator and dedicated HTML template and styles. This HTML templates instructs
        that framework how to render the component and CSS stylesheet defines the appearance of the elements within
        component.
    </p>

    <p>
        Components may vary in layout and functionality. There are many "good-practices" how to 
        project components for your application. One of them is a "Component-Container" pattern also 
        known as "Smart and Dumb Components" in Angular environment. Concept is simple - "Container"
        (or a "Smart" component) is responsible for every logic and data flow. "Dumb" component (or "Component" 
        also called "Presentation Component") is responsible for rendering the data and layout.  
        That pattern will be explained in further reading. But as you can see the components 
        can be very simple HTML template but it also can be responsible for very complex logic that 
        can fetch data from server and process it. But starting from starch let me introduce you into basic Angular component.
    </p>

    <p>
        To create a component, you need to create a <code>*.component.ts</code> file where that decorator is
        attached to specific <code>*Component</code> class. Code example is provided below as
        <code>single.component.ts</code>
        in section "Single File Component". Each component could have a set of properties and methods like classic
        TypeScript class.
        Component are strongly encapsulated and without specific properties the data sharing between
        components is not possible. In further reading it will be explained how to do that.
    </p>

    

    <h2>Single File Component</h2>
    <p>
        Single file components are rarely used in Angular but it is possible to use them. This concept assumes
        that you define your component with all logic template and styles in a single file and then you can import
        it in other files. This is the minimal approach.
    </p>
    <label>single.component.ts</label>
    <pre><code [highlight]="code1" [lineNumbers]="true"></code></pre>

    <p>
        <code>@Component()</code> decorator require at least two properties to properly define a component.
    </p>
    <ul>
        <li>
            <code>selector</code> - the first one that defines the tag name of
            the component that will be associated with that class.
        </li>
        <li>
            <code>template</code> or <code>templateUrl</code> - that defines the HTML 
            template or file location of the HTML template that will be rendered with that component.
        </li>
        <li>
            <code>styles</code> or <code>stylesUrls</code> (Optional) - that defines the CSS definitions or stylesheet file location.
        </li>
    </ul>


    <h2>Basic Angular Component</h2>
    <p>
        More often you will see the component definition with separated <code>*.html</code> and <code>*.css</code> 
        files from the main <code>*.component.ts</code> file. This is the recommended approach that helps you to organize
        your code and makes it easier to maintain. Also the text editor will be able highlight the code and give you 
        additional linting and code completion. But the major advantage is that you starting to using the MVC design pattern where
        the V (View) is the component HTML definition and C (Controller) is the component class. But where is the M (Model)?
        The Model could be in external files that define additional classes and interfaces.
    </p>
    <label>basic.component.ts</label>
    <pre><code [highlight]="code2" [lineNumbers]="true"></code></pre>

    <h2>Component usage</h2>
    <p>
        When the component class definition is done, now it's time to use it. So to do that in HTML template
        of other component you need to add markup that you defined in 'selector' section in previous
        example. And that's it! Each Angular project has root component that by default is named <code>app.component.ts</code>.
        So in related <code>app.component.html</code> file you can add the following code to see your new component: 
    </p>
    <label>app.component.html</label>
    <pre><code [highlight]="code3" [lineNumbers]="true"></code></pre>
    <p>
        Make sure that your component has been added to valid module. By default for
        Angular the root module is defined in <code>app.module.ts</code> file.
        Users can also define their own modules. That feature helps to easily
        maintain the project structure.
    </p>

    <label>app.module.ts</label>
    <pre><code [highlight]="code4" [lineNumbers]="true"></code></pre>

    <h2>Root Component</h2>
    <p>
        Each framework must have its own beginning where everything is initialized. In Angular project you can find the <code>index.html</code> file and
        if you open that file you will see that inside the body tag there is a 'app-root' selector. This is the reference 
        to the root component that by default is called <code>app.component.ts</code>. It is not strict definition and you you want
        to change it, you can do it.
    </p>

</div>
